routes/web.php
<?php

Route::group(['middleware' => ['web']], function(){
  // Authentication Routes
  Route::get('auth/login', 'Auth\AuthController@getlogin');
  Route::post('auth/login', 'Auth\AuthController@postlogin');
  Route::get('auth/logout', 'Auth\AuthController@getogout');

  // Registration Routes
  Route::get('auth/register', 'Auth\AuthController@getregister');
  Route::post('auth/register', 'Auth\AuthController@postregister');

  Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@single'])->where('slug', '[w\d\-\_]+');
  Route::get('blog', ['uses' => 'BlogController@index', 'as' => 'blog.index']);
  Route::get('/',       ['uses' => 'HomeController@home',     'as' => 'home' ]);
  Route::get('about',   ['uses' => 'HomeController@about',    'as' => 'about' ]);
  Route::get('contact', ['uses' => 'HomeController@contact',  'as' => 'contact' ]);
  Route::resource('posts', 'PostController');

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
  
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $fillable = [
      'name', 'email', 'password'
    ];

    protected $hidden = [
      'password', 'remember_token'
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Http\Requests;

class BlogController extends Controller
{
    public function index()
    {
      $post = Post::paginate(10);
      return view('blog.index')->with('posts', $post);
    }
    public function single($slug)
    {
      // fetch on the DB based on slug
      $post = Post::where('slug', '=', $slug)->first();

      // return the view and pass in the post oci_fetch_object
      return view('blog.single')->with('posts', $post);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Http\Requests;
use DB;

class HomeController extends Controller
{
  public function home()
  {
    $posts = Post::OrderBy('created_at', 'desc')->paginate(10);
    return view('page.home')->with('posts', $posts);
  }

    public function about()
    {
      return view('page.about');
    }

    public function contact()
    {
      return view('page.contact');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Post;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // create a variable and store all the blog posts in it from the database
        $posts = Post::OrderBy('created_at', 'desc')->paginate(10);

        // return a view and pass in the above variable
        return view('posts.index')->with('posts', $posts);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate the data
        $this->validate($request, [
          'title' =>  'required|max:225',
          'slug'  =>  'required|alpha_dash|min:5|max:255',
          'body'  =>  'required'
        ]);
        // store in the database
        $post = new Post;

        $post->title = $request->title;
        $post->slug  = $request->slug;
        $post->body = $request->body;
        $post->save();

        Session::flash('success', 'the post was successfully posted');

        // redirect to another page
        return redirect()->route('posts.show', $post->id);
     }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $post = Post::find($id);

        return view('posts.show')->with('post', $post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        return view('posts.edit')->with('post', $post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validate the data
        $post = Post::find($id);

        if ($request->input('slug') == $post->slug) {
          $this->validate($request, [
            'title' =>  'required|max:255',
            'body'  =>  'required'
          ]);
        }
        else {
          $this->validate($request, [
            'title' =>  'required|max:255',
            'slug'  =>  'required|alpha_dash|min:5|max:255|unique:posts,slug',
            'body'  =>  'required'
          ]);
        }
        
        // Save the data to the database
        $post = Post::find($id);

        $post->title = $request->input('title');
        $post->slug  = $request->input('slug');
        $post->body = $request->input('body');
        $post->save();

        Session::flash('success', 'the post was successfully updated');

        // redirect to another page
        return redirect()->route('posts.show', $post->id);
        // redirect view with flash message to posts.show
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);

        $post->delete();

        Session::flash('success', 'The pos was successfully deleted');

        return redirect()->route('posts.index');
    }

}

resources/views/blog/index.blade.php
@extends('layout.master')
@section('title')
  Blog
@endsection
@section('konten')



  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Blog</h1>
    </div>
  </div>
@foreach($posts as $post)
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>{{ $post->title }}</h2>
      <h5>Published: {{ date('M j, Y', strtotime($post->created_at)) }}</h5>

      <p>{{ substr($post->body, 0, 250) }}{{ strlen($post->body) > 250 ? "..." : "" }}  </p>

      <a href="{{ route('blog.single', $post->id) }}" class="btn btn-primary">Read More</a>
    </div>
  </div>

@endforeach
<div class="row">
  <div class="col-md-12">
    <div class="text-center">
      {!! $posts->links() !!}
    </div>
  </div>
</div>
@endsection

resources/views/include/_message.blade.php
@if(Session::has('success'))
  <div class="alert alert-success" role="alert">
    <strong>Success :</strong> {{ Session::get('success') }}
  </div>
@endif

@if(count($errors) > 0)
  <div class="alert alert-danger" role="alert">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

resources/views/include/header.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="{{ Request::is('about') ? "active navbar-brand" : "navbar-brand" }}" href="/">SantriNgoding  <span class="sr-only">(current)</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="{{ Request::is('blog') ? "active" : "" }}"><a href="{{ route('blog.index') }}">Blog</a></li>
        <li class="{{ Request::is('about') ? "active" : "" }}"><a href="{{ route('about') }}">About</a></li>
        <li class="{{ Request::is('contact') ? "active" : "" }}"><a href="{{ route('contact') }}">Contact</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ route('posts.index') }}">Posts</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {{ Html::style('css/styles.css') }}
    <title>@yield('title')</title>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    @include('include.header')
    <div class="container">
      @include('include._message')
      @yield('konten')
    </div>

    @include('include.footer')

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/page/about.blade.php
@extends('layout.master')
@section('header-about')
  <li class="active"><a href="{{ route('about') }}">About</a></li>
@endsection
@section('header-contact')
  <li><a href="{{ route('contact') }}">Contact</a></li>
@endsection
@section('title')
About
@endsection
@section('konten')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>About Me</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
      </div>
    </div>
  </div>
@endsection

resources/views/page/contact.blade.php
@extends('layout.master')
@section('header-about')
  <li><a href="{{ route('about') }}">About</a></li>
@endsection
@section('header-contact')
  <li class="active"><a href="{{ route('contact') }}">Contact</a></li>
@endsection
@section('title')
About
@endsection
@section('konten')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Contact Me</h1>
        <hr>
        <form class="" action="index.html" method="post">
          <div class="form-group">
            <label name="email">Email :</label>
            <input type="text" name="email" id="email" class="form-control">
          </div>
          <div class="form-group">
            <label name="email">Subject :</label>
            <input type="text" name="subject" id="subject" class="form-control">
          </div>
          <div class="form-group">
            <label name="email">Message :</label>
            <textarea name="message" class="form-control" placeholder="Type your message here...."></textarea>
          </div>
          <input type="submit" name="submit" value="Send Message" class="btn btn-success">
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/page/home.blade.php
@extends('layout.master')
@section('header-about')
  <li><a href="{{ route('about') }}">About</a></li>
@endsection
@section('header-contact')
  <li><a href="{{ route('contact') }}">Contact</a></li>
@endsection
@section('title')
  Beranda
@endsection
@section('konten')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="jumbotron">
          <h1>Welcome to this blog</h1>
          <p class="lead">Thank you for visiting</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Popular Post</a></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        <div class="post">
          @foreach($posts as $post)
          <h3>{{ $post->title }}</h3>
          <p>
            {{ substr($post->body, 0, 50) }} {{ strlen($post->body) > 50 ? "..." : "" }}
          </p>
          <a href="{{ route('posts.show', $post->id) }}" class="btn btn-primary">Read More</a>
        @endforeach
        </div>
      </div>
      <div class="col-md-3 col-md-offset-1">
          <h2>Sidebar</h2>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="text-center">
        {!! $posts->links(); !!}
      </div>
    </div>
  </div>
@endsection

resources/views/posts/create.blade.php
@extends('layout.master')
@section('title')
Post Something
@endsection
@section('konten')
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h1>Create New Post</h1>
        <hr>
        {!! Form::open(['route' => 'posts.store']) !!}
          {{ Form::label('title', 'Title :') }}
          {{ Form::text('title', null, ['class' => 'form-control']) }}

          {{ Form::label('slug', 'Slug :') }}
          {{ Form::text('slug', null, ['class' => 'form-control', 'required' => '', 'minlength' => '5', 'maxlength' => '255']) }}

          {{ Form::label('body', 'Body :', ['style' => 'margin-top: 10px']) }}
          {{ Form::textarea('body', null, ['class' => 'form-control']) }}

          {{ Form::submit('Publish', ['class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px']) }}
        {!! Form::close() !!}
      </div>
    </div>
  </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layout.master')
@section('title')
  Edit
@endsection
@section('konten')
  <div class="row">
    {!! Form::model($post, ['route' => ['posts.update', $post->id], 'method' => 'PUT' ]) !!}
    <div class="col-md-8">
      {{ Form::label('title', 'Title') }}
      {{ Form::text('title', null, ['class' => 'form-control input-lg']) }}

      {{ Form::label('slug', 'Slug', ['class' => 'form-spacing-top']) }}
      {{ Form::text('slug', null, ['class' => 'form-control']) }}

      {{ Form::label('body', 'Body', ['class' => 'form-spacing-top']) }}
      {{ Form::textarea('body', null, ['class' => 'form-control']) }}


    </div>
    <div class="col-md-4">
      <div class="well">
        <dl class="dl-horizontal">
          <dt>Created At :</dt>
          <dd>{{ date('H:i M j, Y', strtotime($post->created_at)) }}</dd>
        </dl>

        <dl class="dl-horizontal">
          <dt>Last Updated :</dt>
          <dd>{{ date('H:i M j, Y', strtotime($post->updated_at)) }}</dd>
        </dl>

        <hr>
        <div class="row">
          <div class="col-sm-6">
            {!! Html::linkRoute('posts.show', 'Cancel', [$post->id], ['class' => 'btn btn-danger btn-block']) !!}
          </div>

          <div class="col-sm-6">
            {{ Form::submit('Save Changes', ['class' => 'btn btn-success btn-block']) }}
          </div>
        </div>
      </div>
    </div>
    {!! Form::close() !!}
  </div> <!-- end of .row -->

@endsection

resources/views/posts/index.blade.php
@extends('layout.master')
@section('title')
  Main Dashboard
@endsection
@section('konten')
  <div class="row">
    <div class="col-md-10">
      <h1>All Post</h1>
    </div>
    <div class="col-md-2">
      {!! Html::linkRoute('posts.create', 'Create New Post', [null], ['class' => 'btn btn-lg btn-block btn-warning btn-h1-spacing']) !!}
    </div>
    <div class="col-md-12">
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-condensed">
        <thead>
          <th> # </th>
          <th>title</th>
          <th>Body</th>
          <th>Created At</th>
          <th></th>
        </thead>
        <tbody>
          @foreach($posts as $post)
            <tr>
              <td>{{ $post->id }}</td>
              <td>{{ $post->title }}</td>
              <td>{{ substr($post->body, 0, 50) }} {{ strlen($post->body) > 50 ? "..." : "" }}</td>
              <td>{{ date('M j, Y', strtotime($post->created_at)) }}</td>
              <td>
                <a href="{{ route('posts.destroy', $post->id) }}"  class="btn-primary btn"><i class="glyphicon glyphicon-eye-open"></i></a>
                <a href="{{ route('posts.edit', $post->id) }}" class="btn-info btn"><i class="glyphicon glyphicon-pencil"></i></a>
              </td>
            </tr>


            <tr></tr>
          @endforeach
        </tbody>
      </table>
      <div class="text-center">
        {!! $posts->links(); !!}
      </div>
    </div>
  </div>
@endsection

resources/views/posts/show.blade.php
@extends('layout.master')
@section('title')
  Show
@endsection
@section('konten')

<div class="row">
  <div class="col-md-8">
    <h1>{{ $post->title }}</h1>
    <p class="lead">
      {{ $post->body }}

    </p>
  </div>
  <div class="col-md-4">
    <div class="well">
      <dl class="dl-horizontal">
        <label>Url :</label>
        <p><a href="{{ url($post->slug) }}">{{ url($post->slug) }}</a></p>
      </dl>

      <dl class="dl-horizontal">
        <label>Created At :</label>
        <p>{{ date('H:i M j, Y', strtotime($post->created_at)) }}</p>
      </dl>

      <dl class="dl-horizontal">
        <label>Last Updated :</label>
        <p>{{ date('H:i M j, Y', strtotime($post->updated_at)) }}</p>
      </dl>

      <hr>
      <div class="row">
        <div class="col-sm-6">

          {!! Html::linkRoute('posts.edit', 'Edit', [$post->id], ['class' => 'btn btn-primary btn-block']) !!}
        </div>

        <div class="col-sm-6">
          {!! Form::open(['route' => ['posts.destroy', $post->id], 'method' => 'DELETE']) !!}

            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block']) !!}

          {!! Form::close() !!}
        </div>
      </div>
      <div class="row">
        <div class="col-md-12" style="margin-top: 10px;">
          <a href="{{ route('posts.index') }}" class="btn btn-default btn-block">Back</a>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection